name: Shell

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Shell - View environment
        run: |
          uname -a
          printenv | sort

