name: Experiment

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3


      - name: Run Experiment
        uses: szabgab/github-action-experiment
        with:
          name: Foo


