name: Experiment

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Single command
        run: echo Hello World!

      - name: uname - pwd - ls
        run: |
          uname
          echo "-----"
          pwd
          echo "-----"
          ls -l

      - name: Show env
        run: |
          printenv | sort

