name: Experiment

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

#      - name: Run Experiment
#        uses: szabgab/github-actions-python@657510231202a336fdf002fde09372c35c4ef19a

#      - name: Run Experiment
#        uses: szabgab/github-actions-experiment@main
#        with:
#          name: Foo

      - name: Show env
        env:
          SOME_VARIABLE: some value
        run: |
          show_env.sh

