name: Shell

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: View environment
        run: |
          uname -a
          printenv | sort

