name: Solr

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 5 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        solr: ['latest']
    services:
      solr:
        image: solr:${{matrix.solr}}

    runs-on: ubuntu-latest
    container: ubuntu:22.10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install curl and ping
        run: |
          apt-get update
          apt-get install -y curl

      - name: Solr with curl
        run: |
          set -x
          curl http://solr:8983/solr/

